apps/users/urls.py
from django.conf.urls import patterns, include, url

from .views import LoginView, PerfilView, PerfilEditView

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^salir/$', 'apps.mycontrol.views.LogOut', name='logout'),
    #url(r'^perfil/(?P<pk>\d+)$', PerfilView.as_view(), name='perfil'),
    url(r'^perfil/$', PerfilView.as_view(), name='perfil'),
    url(r'^perfil-editar/$', PerfilEditView.as_view(), name='perfileditar'),
    # url(r'^perfil-editar/(?P<pk>\d+)$', PerfilEditView.as_view(), name='perfileditar'),
)

mycontrol/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mycontrol.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('apps.mycontrol.urls', namespace="mycontrol_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += (
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
			{'document_root':settings.MEDIA_ROOT,}
		),
	)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager, models.Manager):

	def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):

		email = self.normalize_email(email)
		if not email:
			raise ValueError('El email debe ser obligatorio')
		user = self.model(username = username, email= email, is_active=True, is_staff = is_staff, is_superuser = is_superuser)
		user.set_password(password)
		user.save(using = self._db)
		return user

	def create_user(self, username, email, password=None, **extra_fields):
		return self._create_user(username, email, password, False, False, **extra_fields)


	def create_superuser(self, username, email, password=None, **extra_fields):
		return self._create_user(username, email, password, True, True, **extra_fields)



class User(AbstractBaseUser, PermissionsMixin):

	username = models.CharField(max_length=100, unique=True)
	email = models.EmailField()
	# codigo_empleado = models.PositiveIntegerField()
	nombre = models.CharField(max_length=100)
	apellido = models.CharField(max_length=100)
	avatar = models.ImageField(upload_to = 'users', blank=True, null=True)

	objects = UserManager()

	is_active = models.BooleanField(default=True)
	is_staff = models.BooleanField(default=False)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email']

	def get_short_name(self):
		return self.username

apps/users/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

from .models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30,
                            widget= forms.TextInput(attrs={
                                'class' : 'form-control',
                                'placeholder' : 'Ingrese su Usuario',
                                'required' : 'True'
                            }))
    password = forms.CharField(max_length=30,
                            widget = forms.PasswordInput(attrs={
                                'class' : 'form-control',
                                'placeholder' : 'Ingrese su Contraseña',
                                'required' : 'True'
                            }))


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        #exclude = ('email',)

        widgets = {
            'email' : forms.TextInput(attrs={'class' : 'form-control', 'readonly':'readonly'}),
            'username' : forms.TextInput(attrs={'class' : 'form-control'}),
            'nombre' : forms.TextInput(attrs={'class' : 'form-control'}),
            'apellido' : forms.TextInput(attrs={'class' : 'form-control'}),
            'avatar' : forms.FileInput(attrs={'class' : 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class' : 'form-control'}),
        }




# class ProductoForm(forms.ModelForm):
# class Meta:
# model = Producto
# exclude = ('slug',)
# widgets = {
# 'barcode' : forms.NumberInput(attrs={'class' : 'form-control'}),
# 'nombre' : forms.TextInput(attrs={'class' : 'form-control'}),
# 'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'rows' : '2'}),
# 'marca' : forms.Select(attrs={'class' : 'form-control'}),
# 'existencia' : forms.NumberInput(attrs={'class' : 'form-control'}),
# 'precioVenta' : forms.NumberInput(attrs={'class' : 'form-control'}),
# 'precioCompra' : forms.NumberInput(attrs={'class' : 'form-control'}),
# 'precioPorMayor' : forms.NumberInput(attrs={'class' : 'form-control'}),
# 'imagen' : forms.FileInput(attrs={'class' : 'form-control'}),
# 'sucursal' : forms.Select(attrs={'class' : 'form-control'}),
# 'proveedor' : forms.Select(attrs={'class' : 'form-control'}),
# 'categoria' : forms.Select(attrs={'class' : 'form-control'}),
# 'user' : forms.Select(attrs={'class' : 'form-control'})
# }

apps/users/views.py
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, FormView
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from .forms import LoginForm, UserEditForm

from .models import User
#from apps.users.models import User

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return redirect('/')
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

def LogOut(request):
	auth_logout(request)
	return redirect('/')

class PerfilView(LoginRequiredMixin, TemplateView):

    template_name = 'users/perfil_user.html'
    login_url = "/login/"

    def get_context_data(self, **kwargs):
        context = super(PerfilView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(pk = self.request.user.id)
        return context


class PerfilEditView(LoginRequiredMixin, FormView):

    template_name = 'users/editperfil_user.html'
    success_url = reverse_lazy('user_app:perfil')
    model = User
    form_class = UserEditForm
    login_url = "/login/"

    def get_context_data(self, **kwargs):
        context = super(PerfilEditView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(pk = self.request.user.id)
        return context

    def get_initial(self):
        data = {
            'username' : self.request.user.username,
            'nombre' : self.request.user.nombre,
            'apellido' : self.request.user.apellido,
            'email' : self.request.user.email,
        }
        return data

apps/users/templates/users/editperfil_user.html
{% extends "base.html" %}

{% block title %} {{ block.super }} | Perfil{% endblock title %}

{% block body %}
    {% include "navbar.html" %}
    <!--<div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'users_app:perfil' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
            </h4>
        </div>

        <div class="row">
            <div class="col-md-12 well">
                <form role="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <strong>
                        <p class="text-center lead">
                        <span class="glyphicon glyphicon-info-sign"></span> Datos a Modificar
                        </p>
                    </strong>
                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.errors }}
                    </div>
                    {% endif %}

                    <div class="col-md-6 form-group">
                        <label class="label-control">{{ form.username.label_tag }}</label>
                        {{ form.username }}
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-7 form-group">
                            <label class="label-control">{{ form.avatar.label_tag }}</label>
                            {{ form.avatar }}
                        </div>
                    <div class="col-md-5" style="margin-top:-4em;">
                        {% if user.avatar %}
                        <img src="{{user.avatar.url}}" alt="{{user.username}}" class="img-thumbnail" width="200" style="height:120px !important;">
                        {% else %}
                        <img src="/media/default.png" alt="{{user.username}}" class="img-thumbnail" width="200" style="height:120px !important;">
                        {% endif %}
                    </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="label-control">{{ form.email.label_tag }}</label>
                        {{ form.email }}
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="label-control">{{ form.nombre.label_tag }}</label>
                        {{ form.nombre }}
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="label-control">{{ form.apellido.label_tag }}</label>
                        {{ form.apellido }}
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="label-control">{{ form.password.label_tag }}</label>
                        {{ form.password }}
                    </div>
                    <div class="col-md-12 col-md-offset-5 form-group">
                        <button type="submit" class="btn btn-lg btn-primary">Editar</button>
                    </div>
                </form>
                </div>
        </div>

    </div>-->




    <div class="container well">
        <h1>Editar Perfil</h1>
      	<hr>
    	<div class="row">
        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <!-- left column -->
          <div class="col-md-3">
            <div class="text-center">
              {% if user.avatar %}
                  <img src="{{MEDIA_URL}}{{user.avatar}}" class="img-thumbnail img-responsive" alt="avatar" width="300">
                  <h6>Sube una foto diferente...</h6>
                  {{ form.avatar }}
              {% else %}
                  <img src="{{MEDIA_URL}}default.png" class="img-thumbnail img-responsive" alt="avatar" width="300">
                  <h6>Sube una foto diferente...</h6>
                  {{ form.avatar }}
              {% endif %}
            </div>
          </div>
          <!-- edit form column -->
          <div class="col-md-9 personal-info">
            <!--<div class="alert alert-info alert-dismissable">
              <a class="panel-close close" data-dismiss="alert">×</a>
              <i class="fa fa-coffee"></i>
              This is an <strong>.alert</strong>. Use this to show important messages to the user.
            </div>-->
            <h3>Informacion Personal</h3>
              <div class="form-group">
                <label class="col-lg-3 control-label">{{ form.username.label_tag }}</label>
                <div class="col-lg-8">
                  {{ form.username }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-lg-3 control-label">{{ form.nombre.label_tag }}</label>
                <div class="col-lg-8">
                  {{ form.nombre }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-lg-3 control-label">{{ form.apellido.label_tag }}</label>
                <div class="col-lg-8">
                  {{ form.apellido }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-lg-3 control-label">{{ form.email.label_tag }}</label>
                <div class="col-lg-8">
                  {{ form.email }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-3 control-label">Contraseña:</label>
                <div class="col-md-8">
                  {{ form.password }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-3 control-label">Confirm Contraseña:</label>
                <div class="col-md-8">
                  {{ form.password }}
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-8">
                  <input type="submit" class="btn btn-primary" value="Guardar Cambios">
                  <span></span>
                  <input type="reset" class="btn btn-default" value="Cancelar">
                </div>
              </div>
            </form>
          </div>
      </div>
    </div>
    <hr>


{% endblock %}

apps/users/templates/users/login.html
{% extends "base.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">My Control</h1>
            <p>&nbsp;</p>
        </div><!-- col-md-12 -->
    </div><!-- /row -->
    <div class="row">
        <div class=" col-md-12 text-center">
            <div class="col-md-push-4 col-md-4 text-left">
                <form role="form" method="POST">{% csrf_token %}
                    <h4 class="text-center">Ingresa tus Datos:</h4>
                    {% if form.non_field_errors %}
                      <div id="errors-alert" class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {% for error in form.non_field_errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
                    {% endif %}
                    <div class="form-group">
                      <!--<input type="text" class="form-control" name="name" value="" placeholder="Usuario">-->
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                      <!--<input type="password" class="form-control" name="name" value="" placeholder="Contraseña">-->
                        {{ form.password }}
                        {{ form.password.errors.as_text }}
                    </div>
                    <p>
                      <a href="#">¿Olvidaste tu contraseña?</a>
                    </p>
                    <button type="submit" name="login_form" class="btn btn-success btn-lg btn-block">Log in</button>
                </form>
            </div><!-- col-md-6 -->

        </div><!-- col-md-12 -->

    </div><!-- /row -->

</div>
{% endblock %}

apps/users/templates/users/perfil_user.html
{% extends "base.html" %}

{% block title %} {{ block.super }} | Perfil{% endblock title %}

{% block body %}
    {% include "navbar.html" %}
    <div class="container">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad" >
        <div class="panel panel-perfil">
          <div class="panel-heading">
            <h3 class="panel-title">{{user.nombre}} {{user.apellido}}</h3>
          </div>
          <div class="panel-body">
            <div class="row">
            <div class="col-md-3 col-lg-3 " align="center">
              {% if user.avatar %}
                  <img src="{{MEDIA_URL}}{{user.avatar}}" class="img-thumbnail img-responsive" alt="avatar" width="300">
                  <h6>Sube una foto diferente...</h6>
                  <a href="{% url 'users_app:perfileditar' %}" type="button" class="btn btn-default"><i class="glyphicon glyphicon-edit"></i> Editar</a>
              {% else %}
                  <img src="{{MEDIA_URL}}default.png" class="img-thumbnail img-responsive" alt="avatar" width="300">
                  <h6>Sube una foto diferente...</h6>
                  <a href="{% url 'users_app:perfileditar' %}" type="button" class="btn btn-default"><i class="glyphicon glyphicon-edit"></i> Editar</a>
              {% endif %}
            </div>
            <div class=" col-md-9 col-lg-9 ">
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <th>Usuario</th>
                    <td>{{user.username}}</td>
                  </tr>
                  <tr>
                    <th>Nombre</th>
                    <td>{{user.nombre}}</td>
                  </tr>
                  <tr>
                    <th>Apellido</th>
                    <td>{{user.apellido}}</td>
                  </tr>
                  <tr>
                    <th>Email</th>
                    <td>{{user.email}}</td>
                  </tr>
                  <tr>
                    <th>Estado</th>
                    <td>
                      {%if user.is_active %}
                        <span class="label label-success">ACTIVO</span>
                      {% else %}
                        <span class="label label-danger">INACTIVO</span>
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th>Permiso</th>
                      <td>
                        {%if user.is_staff %}
                          <span class="label label-success">ADMINISTRADOR</span>
                        {% else %}
                          <span class="label label-danger">USUARIO</span>
                        {% endif %}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <a href="/" class="btn btn-default">
            <span class="glyphicon glyphicon-chevron-left"></span>
            Regresar
          </a>
          <span class="pull-right">
            <a href="{% url 'users_app:perfileditar' %}" type="button" class="btn btn-default"><i class="glyphicon glyphicon-edit"></i> Editar Perfil</a>
          </span>
        </div>

      </div>
    </div>

  </div>
{% endblock %}