apps/mycontrol/urls.py
from django.conf.urls import patterns, include, url

from .views import MainView

urlpatterns = patterns('',
    url(r'^$', MainView.as_view(), name='main'),
    # url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # url(r'^salir/$', 'apps.mycontrol.views.LogOut', name='logout'),
)

apps/users/urls.py
from django.conf.urls import patterns, include, url

from .views import LoginView, PerfilView, PerfilEditView

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^salir/$', 'apps.mycontrol.views.LogOut', name='logout'),
    #url(r'^perfil/(?P<pk>\d+)$', PerfilView.as_view(), name='perfil'),
    url(r'^perfil/$', PerfilView.as_view(), name='perfil'),
    url(r'^perfil-editar/$', PerfilEditView.as_view(), name='perfileditar'),
    # url(r'^perfil-editar/(?P<pk>\d+)$', PerfilEditView.as_view(), name='perfileditar'),
)

mycontrol/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mycontrol.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('apps.mycontrol.urls', namespace="mycontrol_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += (
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
			{'document_root':settings.MEDIA_ROOT,}
		),
	)

apps/mycontrol/models.py
from django.db import models

# Create your models here.

apps/mycontrol/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30,
                            widget= forms.TextInput(attrs={
                                'class' : 'form-control',
                                'placeholder' : 'Ingrese su Usuario',
                                'required' : 'True'
                            }))
    password = forms.CharField(max_length=30,
                            widget = forms.PasswordInput(attrs={
                                'class' : 'form-control',
                                'placeholder' : 'Ingrese su Contraseña',
                                'required' : 'True'
                            }))

# class RFPAuthForm(AuthenticationForm):
#     username = forms.CharField(widget=TextInput(attrs={'class': 'span2','placeholder': 'Email'}))
#     password = forms.CharField(widget=PasswordInput(attrs={'class': 'span2','placeholder':'Password'}))
    # def clean(self):
    #     if self.cleaned_data.get('username') and self.cleaned_data.get('password'):
    #         username = self.cleaned_data.get('username')
    #         username_exist = User.objects.filter(username = username).exists()

    #     if username_exist:
    #         user = User.objects.get(username = username)

    #     if not user.check_password(self.cleaned_data.get("password")):
    #         self.add_error('password', 'La contraseña es incorrecta')

    #     else:
    #         self.add_error('username', 'El usuario no existe!')

apps/mycontrol/views.py
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters

from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse_lazy, reverse
#from django.contrib.auth import authenticate, logout
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, FormView
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from .forms import LoginForm



class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'
    login_url = "/login/"


# class LoginView(TemplateView):

# 	template_name = 'login.html'
#     #form_class = LoginForm
# 	success_url = reverse_lazy('main')
# 	# form_class = LoginForm
# 	# success_url = reverse_lazy('home')
#     def post(self, request, *args, **kwargs):
#         request.POST['email'], request.POST['password']

#         user = authenticate(username=request.POST['email'], password='secret')
#         if user is not None:
#             # the password verified for the user
#             if user.is_active:
#                 print("User is valid, active and authenticated")
#             else:
#                 print("The password is valid, but the account has been disabled!")
#         else:
#             # the authentication system was unable to verify the username and password
#             print("The username and password were incorrect.")

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'login.html'

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return redirect('/')
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    # @method_decorator(sensitive_post_parameters('password'))
    # def dispatch(self, request, *args, **kwargs):
    #     request.session.set_test_cookie()
    #     return super(LoginView, self).dispatch(request, *args, **kwargs)

    # def get(self, request):
    #     if not self.request.user.is_authenticated:
    #         return super(LoginView, self).get(self, request)
    #     else:
    #         print self.request.user
    #         return redirect("/")
# class LogoutView(View):
#     def get(self, request, *args, **kwargs):
#         auth_logout(request)
#         return redirect('/')
def LogOut(request):
	auth_logout(request)
	return redirect('/')

# from django.conf import settings
# from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth import login as auth_login, logout as auth_logout
# from django.http import HttpResponseRedirect
# from django.utils.decorators import method_decorator
# from django.views.decorators.debug import sensitive_post_parameters
# from django.views import FormView, View
#
# class Login(FormView):
#     form_class = AuthenticationForm
#
#     def form_valid(self, form):
#         redirect_to = settings.LOGIN_REDIRECT_URL
#         auth_login(self.request, form.get_user())
#         if self.request.session.test_cookie_worked():
#             self.request.session.delete_test_cookie()
#         return HttpResponseRedirect(redirect_to)
#
#     def form_invalid(self, form):
#         return self.render_to_response(self.get_context_data(form=form))
#
#     @method_decorator(sensitive_post_parameters('password'))
#     def dispatch(self, request, *args, **kwargs):
#         request.session.set_test_cookie()
#         return super(Login, self).dispatch(request, *args, **kwargs)
#
# class Logout(View):
#     def get(self, request, *args, **kwargs):
#         auth_logout(request)
#         return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)

apps/mycontrol/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../../favicon.ico">
    <title>{% block title %}My Control{% endblock title %}</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <script src="{% static "js/jquery.min.js" %}"></script>
  </head>
  <body>
    <div class="container">
    {% block body %}
    {% endblock body %}
    </div>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
  </body>
</html>

apps/mycontrol/templates/index.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Principal{% endblock %}


{% block body %}
{% include "navbar.html" %}
  <h1>Hola!</h1>
{% endblock %}

apps/mycontrol/templates/navbar.html
<div class="navbar navbar-default navbar-blue navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        	<a href="/" class="navbar-brand">My Control</a>
        	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        		<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
        	</button>
        </div>
	    <div class="navbar-collapse collapse" id="navbar-main">
	        <ul class="nav navbar-nav">
	            <!--<li>
	              	<a href="#" class="active">
	              		<span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
	              		Dashboard
	              	</a>
	            </li>-->
	            <li>
	            	<a href="" >
	              		<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
	              		Registros
	              	</a>
	            </li>
	            <li>
	            	<a href="#">
	            		<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
	            		Ventas
	            	</a>
	            </li>
	            <li class="dropdown">
	            	<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Simplex <span class="caret"></span></a>
		            <ul class="dropdown-menu" aria-labelledby="download">
		                <li><a href="http://jsfiddle.net/bootswatch/3he50zsf/">Open Sandbox</a></li>
		                <li class="divider"></li>
		                <li><a href="./bootstrap.min.css">bootstrap.min.css</a></li>
		                <li><a href="./bootstrap.css">bootstrap.css</a></li>
		                <li class="divider"></li>
		                <li><a href="./variables.less">variables.less</a></li>
		                <li><a href="./bootswatch.less">bootswatch.less</a></li>
		                <li class="divider"></li>
		                <li><a href="./_variables.scss">_variables.scss</a></li>
		                <li><a href="./_bootswatch.scss">_bootswatch.scss</a></li>
		            </ul>
	            </li>
	        </ul>

	        <ul class="nav navbar-nav navbar-right">
	        	{% if user.is_authenticated %}
		        	<li class="dropdown">
		            	<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">
                    <span style="padding-right:0.5em;">
                      {% if user.avatar %}
                        <img src="{{MEDIA_URL}}{{user.avatar}}" alt="avatar" width="60" height="50" style="margin-left:-1em;margin-top: -1.9em;margin-bottom: -1.8em;">
                      {% else %}
                        <img src="{{MEDIA_URL}}default.png" alt="avatar" width="60" height="50" style="margin-left:-1em;margin-top: -1.9em;margin-bottom: -1.8em;">
                      {% endif %}
                    </span>
		            		{# <span class="pull-left glyphicon glyphicon-user" aria-hidden="true" style="font-size:18px;padding-right:0.5em;"></span>#}
		            		{{ user.username|upper}}
		            		<span class="caret"></span>
		            	</a>

			            <ul class="dropdown-menu" aria-labelledby="download">
			                <li>
			                	<a href="#">
			                		Dashboard
			                		<span class="pull-right glyphicon glyphicon-th-large" aria-hidden="true"></span>
			                	</a>
			                </li>
			                <li>
			                	<a href="">
			                		Registros
			                		<span class="pull-right glyphicon glyphicon-list-alt" aria-hidden="true"></span>
			                	</a>
			                </li>
			                <li>
			                	<a href="#">
			                		Ventas
			                		<span class="pull-right glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
			                	</a>
			                </li>
			                <li class="divider"></li>
			                <li>
			                	<a href="#">
			                		Usuarios
			                		<span class="pull-right glyphicon glyphicon-user" aria-hidden="true"></span>
			                	</a>
			                </li>
			                <li>
			                	<a href="{% url 'users_app:perfil' %}">
			                		Perfil
			                		<span class="pull-right glyphicon glyphicon-cog" aria-hidden="true"></span>
			                	</a>
			                </li>
			                <li class="divider"></li>
			                <li>
			                	<a href="{% url 'users_app:logout' %}">
			                		Salir
			                		<span class="pull-right glyphicon glyphicon-log-out" aria-hidden="true"></span>
			                	</a>
			                </li>
			            </ul>
		            </li>
                {% else %}
                    <li><a href="">Registrarse / Login</a></li>
                {% endif %}
	        </ul>
	    </div>
    </div>
</div>